### ISSUE TITLE
ArgumentStorageImpl singleton retains arguments even after resetStubs and resetExpectations calls on the mock

### ISSUE THREAD

**Issue by vladyslavsosiuk** [pirishd/InstantMock#103]
Hi faced an issue when writing an expectation like 
`
 objectUserMock
            .it
            .expect()
            .call(objectUserMock.useObject(Arg.eq(objectStub!)),
                  count: 1)
`

will retain `objectStub` inside `ArgumentStorageImpl.instance` even after calling `resetStubs` and `resetExpectations`.
As a temporary workaround you may use `objectUserMock.expect()` which will clear retained arguments 
Here is an example repo which reproduce the issue https://github.com/vladislavsosiuk/InstantMockRetainArgumentIssue. 
@pirishd  Please let me know if you need more info

**Comment by pirishd** [comment]
Hi @vladislavsosiuk,

Thanks for this bug report, indeed, there is some missing flushing of this singleton instance.
See https://github.com/pirishd/InstantMock/pull/105 for the fix.

This will be included in the next release to be done shortly.

**Comment by vladyslavsosiuk** [comment]
@pirishd great job 👍
