### ISSUE TITLE
Arg.eq with dictionary throws `Ambiguous use of eq`

### ISSUE THREAD

**Issue by armartinez** [pirishd/InstantMock#112]
@pirishd  When trying to use Arg.eq with a dictionary, i.e.

`Arg<[String: Any]>.eq(someDictionary)`

the compiler throws this error: **Ambiguous use of 'eq'**
Is there anything I need to do in order for this to work ?

Thanks and great work on the library :)

**Comment by pirishd** [comment]
Hi,

It should work properly.

This sample builds properly:

```
protocol BasicProtocol {
    func someFunc(_ value: [String: Any])
}


final class BasicMock: Mock, BasicProtocol {

    func someFunc(_ value: [String: Any]) {
        super.call(value)
    }

}
```

```
func testExpect() {
    let mock = BasicMock()
    
    mock.expect().call(mock.someFunc(Arg<[String: Any]>.eq(["toto": 12])))
        
    // or simpler as the type can be inferred
    mock.expect().call(mock.someFunc(Arg.eq(["toto": 12])))
}
```

**Comment by vladyslavsosiuk** [comment]
hi, @armartinez this happens probably due to an optional argument the stubbed method is expecting and the compiler doesn't know which overload of Arg.eq to use. You can either specify type as optional like `Arg<[String: Any]?>.eq(someDictionary)` or explicitly specify type of expression like `{ () -> [String: Any] in Arg.eq(someDictionary) }()` 

```
protocol BasicProtocol {
    func someFunc(_ optionalDictionary: [String: Any]?)
}


final class BasicMock: Mock, BasicProtocol {

    func someFunc(_ optionalDictionary: [String: Any]?) {
        super.call(optionalDictionary)
    }

}
func testExpect() {
    let mock = BasicMock()
    
    mock.expect().call(mock.someFunc(Arg<[String: Any]?>.eq(["toto": 12])))
}
func testExpect_2() {
    let mock = BasicMock()
    
    mock.expect().call(mock.someFunc({ () -> [String: Any] in Arg.eq(["toto": 12]) }()))
}
```
