### ISSUE TITLE
Invalid argument configuration, see Arg class for more information

### ISSUE THREAD

**Issue by igordeoliveirasa** [pirishd/InstantMock#34]
When I stub like this:

                self.modelRepository.stub().call(
                    self.modelRepository
                        .beginTransaction(
                            options: Arg.any()
                    )
                ).andReturn(self.transaction)

**Comment by igordeoliveirasa** [comment]
options is [String: Any]?

**Comment by pirishd** [comment]
This error occurs when the stubbed method and the mock instance are not consistent in the number of args.

Here, I guess the `beginTransaction` method of your mock does not call the framework with the expected number of arguments. It should be something like:
```
func beginTransaction(options: [String: Any]?) -> … {
    super.call(options)
}
```

**Comment by igordeoliveirasa** [comment]
My call is right. I found out that the problem was that my Transaction class was not implementing MockUsable. However, after implementing that, it only returns the default Transaction.any value. It never returns the .andReturns(mockTransaction). 

Could you please help me? Thanks a lot

**Comment by igordeoliveirasa** [comment]
I'm thinking that is because I'm trying to mock/stub a method that returns a Promise, using PromiseKit. Can you help me?

**Comment by igordeoliveirasa** [comment]
Answer is at: #35
