### ISSUE TITLE
Make func equal(to value: MockUsable?) -> Bool throwable

### ISSUE THREAD

**Issue by igordeoliveirasa** [pirishd/InstantMock#38]
I have to make some calls that may throw exceptions inside MockUsable equal method.
What do you think if we could add a Throw option on this method?

Thanks.

**Comment by pirishd** [comment]
I'm not sure to understand what would be the goal for this. Would you please add a detailed case?

Basically, the idea of the `equal` method is to assert equality of 2 instances. If any inner call throws an exception, it should be handled within the `equal` method (with `catch`, `try!`, `try?`…), and not propagated to the upper level.

**Comment by igordeoliveirasa** [comment]
You are right.
