### ISSUE TITLE
I can't use Arg.eq(MyClass.self) neither Arg.eq(MyProtocol.self)

### ISSUE THREAD

**Issue by igordeoliveirasa** [pirishd/InstantMock#39]
Any tip?

**Comment by pirishd** [comment]
Would you please post a detailed case?

I don't get the use of this as `Arg.eq(…)` is dedicated to verify that a call is done with a specific instance of a class, not the type of a class or a protocol.

**Comment by igordeoliveirasa** [comment]
I would like to spy a method that receives a param as: T.Type. How could I do that?

**Comment by igordeoliveirasa** [comment]
example: 
```swift
func myMethod<T>(classType: T.Type) -> T
```

**Comment by igordeoliveirasa** [comment]
I guess I made a mistake. Now it's working... Anyway..
