### ISSUE TITLE
Dictionary containing value as _NSContiguousString. It is not MockUsable

### ISSUE THREAD

**Issue by igordeoliveirasa** [pirishd/InstantMock#40]
Sometimes I receive a dictionary containing strings that are _NSContiguousString type. I don't know why. However, Verifier is not able to cast to MockUsable so as to compare.

Any tip?

**Comment by igordeoliveirasa** [comment]
I've just found out that I have a class that extends NSObject, and when I retrieve ".value(forKey: ..." of a String property, it returns a _NSContiguousString. Anyway, I made a Converter that resolves from _NSContiguousString to String, and now I suppose it is going to work..

**Comment by abarisain** [comment]
I'm digging this thread back from the grave, but I've ran into the same thing today:

I have a String nested in an Array that is in a Dictionary. InstantMock fails as it can't cast it to MockUsable

```(lldb) po arg as! MockUsable
Could not cast value of type 'Swift.__SharedStringStorage' (0x1ca321558) to 'InstantMock.MockUsable' (0x1ca34a010).
```

I don't believe that it is InstantMock's fault, Swift should be able to cast this to MockUsage: Strings being static should be an implementation detail and they should still conform to the protocol. Maybe this need to be brought up to the Swift team?

A workaround would be to try to cast strings in Verifier.equal, which sounds like a bad fix. I don't see any other solution though.

Note that testing ObjC nested objects is also annoying, as you have to add NSDictionary and NSArray MockUsable
