### ISSUE TITLE
Stubbing same method twice, but returning different on each call

### ISSUE THREAD

**Issue by igordeoliveirasa** [pirishd/InstantMock#41]
How could I do that?

Let's suppose I have this: 

```swift
mock.stub().call(
    mock.bar(arg1: Arg.eq("hello"), arg2: Arg.any())
).andReturn(true)
```

However, its called twice. I would like to start returning true (first call) and finish returning false (second call).

**Comment by pirishd** [comment]
Check out `andReturn(closure: …)` in the [README]( https://github.com/pirishd/InstantMock/blob/dev/README.md#compute-a-return-value) file. That's exactly the aim of this method :)
For an exemple, see the test `testStub_returnAndDo` in [BasicMockTests.swift](https://github.com/pirishd/InstantMock/blob/dev/Tests/InstantMockTests/Integration%20Tests/BasicMockTests.swift).

**Comment by igordeoliveirasa** [comment]
Alright, so I gotta have a flag control outside of stub, right? If yes, let's close this issue. Thanks!

**Comment by pirishd** [comment]
Yes that's it
