### ISSUE TITLE
Mocking variables (get and set)

### ISSUE THREAD

**Issue by igordeoliveirasa** [pirishd/InstantMock#45]
Is there any way to mock variables?

Suppose this class:

```swift
class Car {
   var brand: String?
}
```

And I'd like to have a MockCar, which I could return my pre-determined brand.

Thanks.

**Comment by pirishd** [comment]
It is possible for getters, as long as the variable is defined in a protocol.

For instance, 
```swift
protocol Car {
   var brand: String?
}

class MockCar: Mock, Car {
    var brand: String? {
         return super.call()
    }
}
```

For setters, it is currently not possible, as there is a need to grab the value set, in some ways.
Anyway, I imagine a syntax like:
```swift
mock.expect().setter().call(mock.brand).withValue(Arg.eq("SomeBrand"))
```

**Comment by igordeoliveirasa** [comment]
great! how are you, @pirishd ? It looks like you disappeared!!

**Comment by pirishd** [comment]
I'm good @igordeoliveirasa, thanks. Though I wish I could spend more time on the project :)

**Comment by pirishd** [comment]
It is now possible to mock setters from version 2.1.0.
See [mocking properties](https://github.com/pirishd/InstantMock/tree/master#properties) and [syntax](https://github.com/pirishd/InstantMock/tree/master#properties-1).
