### ISSUE TITLE
Key order dependent dictionary comparison

### ISSUE THREAD

**Issue by Kotevode** [pirishd/InstantMock#70]
Hi.

After swift 5 migration we faced a problem: expectations with dictionary arguments are not always working. According to the investigation the reason of that behaviour is a dictionary comparison algorithm. As keys array order is generally unpredictable the next test is failing floatly:
```
    func testEqual_toWrongOrder() {
        let dict1: [String: Any] = [
            "foo": 1,
            "bar": 2
        ]
        let dict2: [String: Any] = [
            "bar": 2,
            "foo": 1
        ]

        XCTAssertTrue(dict1.equal(to: dict2))
    }
```

**Comment by pirishd** [comment]
Hi,

Thanks for the feedback! Indeed the comparison for dictionaries was wrong…
See https://github.com/pirishd/InstantMock/pull/71 for the fix.

I plan to release a new version in the next few days.
