### ISSUE TITLE
Problem adding MockUsable extension

### ISSUE THREAD

**Issue by ifau** [pirishd/InstantMock#74]
XCode 10.2.1 (10E1001)
InstantMock (2.5.0)

I created a new XCode project and installed InstantMock via Cocoapods. My `Podfile` is
```ruby
platform :ios, '10.0'
use_frameworks!

target 'MyApp' do

    target 'MyAppTests' do
        pod 'InstantMock'
    end
end
```

I created protocol with function that contains `UInt` parameter

```swift
protocol DatabaseService {    
    func fetchMessages(count: UInt, completion: @escaping ([String]) -> ())
}
```

Because InstantMock does not support `UInt` type by default, I added extension `UInt+MockUsable` with target membership assigned to `MyAppTests` target

```swift
extension UInt: MockUsable {
    
    public static let any = 49
    
    public static var anyValue: MockUsable {
        return UInt.any
    }
    
    public func equal(to value: MockUsable?) -> Bool {
        guard let uintValue = value as? UInt else { return false }
        return self == uintValue
    }
}
```

Then I created a simple test

```swift
func testThatControllerWillFetchMessagesOnAppearEvent() {
    
    let controller = MessagesViewController()
    let databaseServiceMock = DatabaseServiceMock()
    controller.databaseService = self.databaseServiceMock

    // when
    controller.viewWillAppear(false)
    
    // then
    databaseServiceMock.expect().call(databaseServiceMock.fetchMessages(count: Arg.any(), completion: Arg.closure()))
}

class DatabaseServiceMock: Mock, DatabaseService {
    
    func fetchMessages(count: UInt, completion: @escaping ([String]) -> ()) {
        return super.call(count, completion)
    }
}
```

But it falls with error
`Fatal error: Unexpected type, only MockUsable types can be used with any: file Arg.swift, line 126`

That I missed?
Thank you

**Comment by pirishd** [comment]
Hi,

In the `MockUsable` extension, the `any` variable is compiled as an `Int`, not a `UInt`.

Just use `public static let any = UInt(49)` instead of `public static let any = 49`

It should be ok ;)

**Comment by ifau** [comment]
Thank you!
