### ISSUE TITLE
Can't build InstantMock because of bitcode?

### ISSUE THREAD

**Issue by PabloDomine** [pirishd/InstantMock#79]
Error when running tests:
`ld: '/Applications/Xcode 10.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Applications/Xcode 10.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' for architecture arm64`

Xcode 10.3.
Deployment Target 12.3
Swift 5

Podfile:
`target 'RecipePuppy' do
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SDWebImage'

  target 'RecipePuppyUnitTests' do
    use_frameworks!
    inherit! :search_paths
    pod 'InstantMock'
  end
end`

**Comment by pirishd** [comment]
Hi, unfortunately, I don't reproduce (on a new Xcode project with the same configuration, tests build and run properly).

Would you please provide a Xcode sample project where the issue can be reproduced?

**Comment by pirishd** [comment]
No way to reproduce

**Comment by Herbal7ea** [comment]
I'm getting the same @PabloDomine .  Some people are saying to put this in your pods file:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['InstantMock'].include? target.name
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
  end
end
```

I am able to compile with that, but my tests all fail on the device, but they still run in the simulator fine.  Do you see the same on your side?
