### ISSUE TITLE
How to test generic methods that returns closure?

### ISSUE THREAD

**Issue by leandrosilvaeveris** [pirishd/InstantMock#86]
How could I test this method:

```func get<T>(_ url: String, success: @escaping ((_ response: T?) -> Void), failure: @escaping ((_ errorMessage: String) -> Void)) where T: BaseMappable```

Thanks

**Comment by pirishd** [comment]
Do you mean how to make sure this function is called and eventually to mock its behaviour?

If this is what you want to do, the implementation of the mock would be something like:

```
func get<T>(_ url: String, success: @escaping ((T?) -> Void), failure: @escaping ((String) -> Void)) where T : BaseMappable {
    super.call(url, success, failure)
}
```

For the test, the idea would be to use a concrete class of `BaseMappable`, for example:

```
class ConcreteBaseMappable: BaseMappable {
…
}
```

And the test: 
```
func testSomething() {

    mock.expect().call(
        mock.get(Arg.any(), success: Arg.closure() as (ConcreteBaseMappable?) -> Void, failure: Arg.closure())
    )

    // here, the call to the function that calls `get(_, success, failure)`
    ...

    mock.verify()
}
```

Then, if you're interested in mocking the behaviour of the function by calling one of the callbacks, I suggest to capture the closure following https://github.com/pirishd/InstantMock#capturing-a-closure. For example:

```
func testSomething() {
    let captor = ArgumentClosureCaptor<(ConcreteBaseMappable?) -> Void>()

    mock.stub().call(
        mock.get(Arg.any(), success: captor.capture(), failure: Arg.closure())
    ).andDo { _ in 
        captor.value!(…) // here, insert the instance of `ConcreteBaseMappable` you want to inject 
    }

    // here, the call to the function that calls `get(_, success, failure)`
    ...

    mock.verify()
}
```

**Comment by leandrosilvaeveris** [comment]
Thanks for everything. Your answer solved my issue.
