### ISSUE TITLE
Verify if a closure was called

### ISSUE THREAD

**Issue by leandrosilvaeveris** [pirishd/InstantMock#91]
Hi,

Is there a way to know when some closure was called? Follow the example below:

```swift
func someFunction(success: @escaping SuccessClosure, failure: @escaping ErrorClosure) {
    let apiUrl = ""
    networkingProvider.get(apiUrl, success: success, failure: failure)
}
```

I made a mock of networkingProvider and I'd like knowing when the success closure was called. Follow the test example below:

```swift
func test_Example() {
     repository.someFunction(success: Arg.closure(), failure: Arg.closure())
}
```

Is there a way to verify when success/failure closure is called?

**Comment by pirishd** [comment]
Hi,

See this documentation by Apple, for knowing when a closure is called: [XCTestExpectation](https://developer.apple.com/documentation/xctest/asynchronous_tests_and_expectations/testing_asynchronous_operations_with_expectations?language=swift). This is the way I would suggest if you want to test the behaviour of the real instance of your `networkingProvider`.

But, here, if you made a mock of `networkingProvider`, you control the behaviour of your mock, thus you can call the success or failure callback depending on what you want to test. For this, use the way I described in [this issue](https://github.com/pirishd/InstantMock/issues/86). Actually, verifying that a mock calls its own closure doesn't really make sense ;)

**Comment by pirishd** [comment]
Hi @leandrosilvaeveris,

Could I consider this issue as solved, since last comment one month ago?

**Comment by leandrosilvaeveris** [comment]
I think so, thanks
